repos:
  - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.2.0 # replace with the version you want to use
    hooks: # specify the hooks you want to use here
      - id: mix-format
#      - id: mix-test
  -   repo: https://github.com/MarcoGorelli/auto-walrus
      rev: v0.2.2
      hooks:
        -   id: auto-walrus