name: Re-run Failed Workflow

on:
  repository_dispatch:
    types: [ "trigger-rerun" ]

env:
  RUN_ID: ${{ github.event.client_payload.RUN_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "GitHub CLI Version"
          gh --version

      - name: Rerun Failed Jobs Via API
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ github.token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${RUN_ID}/rerun-failed-jobs"
