name: Execute Vulnerability Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 5"

env:
  ELIXIR_VERSION: "1.13.3"
  OTP_VERSION: "24.2.1"
  APPLICATION_WORKING_DIR: ./backend

jobs:
  execute_scan:
    name: Execute Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - name: Output Deps Cache Key
        id: deps_cache_key
        run: |
          echo "::set-output name=DEPS_CACHE_KEY::${{ runner.os }}-Elixir(${{ env.OTP_VERSION }})-OTP(${{ env.ELIXIR_VERSION }})-Mix.LockHash(${{ hashFiles('**/mix.lock') }})"

      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            ${{env.APPLICATION_WORKING_DIR}}/deps
            ${{env.APPLICATION_WORKING_DIR}}/_build
          key: ${{ steps.deps_cache_key.outputs.DEPS_CACHE_KEY }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        working-directory: ${{env.APPLICATION_WORKING_DIR}}
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile

      - name: Execute Report
        id: report_status
        working-directory: ${{env.APPLICATION_WORKING_DIR}}
        run: |
          mix deps.audit

      - name: Echo Scan Exit Code
        if: always()
        run: echo "${{steps.report_status.outcome}}"
      - name: Vulnerabilities Found - Discord notification
        if: always() && steps.report_status.outcome == 'failure'
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "Security Vulnerabilities Identified View Scan Results: ${{ secrets.GITHUB_RUN_URI }}${{ github.run_id }}"
          color: "FF0000",
          username: "GitHub Vulnerability Scanner"
